### ISSUE TITLE
DB Migration Handler

### ISSUE THREAD

**Issue by shawnrc** [shawnrc/quip#3]
Doing db migrations by hand is trash-tier - Liquibase can handle most of this, but it's sort of byzantine and the docs are often unclear or out of date. 

It's unclear if Liquibase is even being actively developed outside of security stuff (there is a link to Datical on the Liquibase navbar, and the first image in their carousel is "10 Reasons Companies Use Datical Over Liquibase"), so worst comes to worst, a switch to Flyway might be the way to go.

**Comment by shawnrc** [comment]
As it turns out, Liquibase does not officially support generating rollbacks for `customSQL` changes, which is understandable, but when using a SQL migrations file, Liquibase doesn't do anything special and instead treats each job as a custom SQL change, generating no rollbacks. 

Since not having to rely on humans to generate rollback code is really important and switching back to XML migrations doesn't sound appealing to contributors, let's see how difficult it is to switch over to Flyway.

**Comment by shawnrc** [comment]
Turns out this is tricker than anticipated. Removed dropwizard-migrations and made the appropriate changes to `QuipService.initialize()`, and now I'm getting a face full of `ClassNotFoundException`:

```
INFO  [2018-02-23 04:51:32,537] org.flywaydb.core.internal.util.VersionPrinter: Flyway Community Edition 5.0.7 by Boxfuse
ERROR [2018-02-23 04:51:32,552] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.lang.ClassNotFoundException:
! at java.lang.Class.forName0(Native Method)
! at java.lang.Class.forName(Class.java:348)
! at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
```

**Comment by shawnrc** [comment]
_Wow_. I think I learned this before, but for future reference, if you try running the shaded dropwizard jar without giving it the path to the config yaml, instead of just saying "Hey dummy, where's the config file you want me to use?" it throws `ClassNotFoundException`. Specifically, the issue is enumerated on the [JDBI page](http://www.dropwizard.io/0.7.1/docs/manual/jdbi.html):

>Note the ClassNotFoundException is thrown by the DBIFactory class when the build method is unable to locate the JDBC driver class. This will cause the service to exit displaying the output of the exception.

But wait, this is for Dropwizard 0.7.1 - the docs for Dropwizard 1.2.2 no longer have this in the DBI module documentation... am I doing it wrong, or are they?

**Comment by shawnrc** [comment]
Okay, turns out, Flyway only supports migration rollbacks (called undos) if you pay $950/year.

Since both Liquibase and Flyway currently both do not offer the project rollback generation, I figure this decision boils down to this:

Either
1. Stick with Flyway because it's more actively developed and might be the better option going forward, or
2. Switch back to Liquibase and convert the migrations file to an XML one to take advantage of rollbacks.

I don't personally mind the XML migrations format. It isn't as bad as most XML configuration usually is. That said, there are quirks in the XML->DDL converter sometimes, and I only can vaguely remember a couple of them off the top of my head (boolean mapping to `BIT`, `BINARY` mapping to `BLOB` rather than the MySQL `BINARY` type). These were for older versions of Liquibase, so I think they ought to be fixed by now, but who knows what other issues might arise? Bugs in the DDL conversion step are apparently not uncommon, and being that I'm not actually a DBA, I feel like I'm not really qualified to deal with the potential issues that might crop up using a dependency that's not as actively developed.
